### ISSUE TITLE
galaxy_extension [OPTIONAL]

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/galaxy#18]
populate 
https://github.com/biocompute-objects/galaxy/blob/cbbe81946233e1e7ac625fc732115b5c23028fa8/lib/galaxy/webapps/galaxy/api/workflows.py#L1142

**Comment by HadleyKing** [comment]
[2.3 Extension Domain "extension_domain"](https://github.com/biocompute-objects/BCO_Specification/blob/1.4.0/docs/bco-domains.md#23-extension-domain-extension_domain)
The extension_domain is a space for a user to add additional structured information that is not defined in the BioCompute shcema. The extension_domain section is not evaluated by checks for BCO validity or computational correctness and as such is the place to add ANY type of additional structured information. We provide two examples that are neither exclusive nor exhaustive.

I would like to add a `galaxy extension` to the documentation. Are there some galaxy specific fields that may be important to record? Like the instance address, or configuration details?

**Comment by nsoranzo** [comment]
Maybe URL and Galaxy version?

**Comment by HadleyKing** [comment]
@nsoranzo what is the best way to pull those two features?
