### ISSUE TITLE
environment_variables

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/galaxy#20]
populate `environment_variables` in `execution_domain`
https://github.com/biocompute-objects/galaxy/blob/cbbe81946233e1e7ac625fc732115b5c23028fa8/lib/galaxy/webapps/galaxy/api/workflows.py#L1139

**Comment by nsoranzo** [comment]
We can extract for each job all the environment variables that were set on the computing node, if the `env` plugin for job metrics is enabled in Galaxy.
But the list of env variables may be quite long and contain variables not really necessary to "configure the execution environment on the target platform", as the standard mandates.

**Comment by HadleyKing** [comment]
- https://docs.galaxyproject.org/en/latest/admin/special_topics/job_metrics.html
- https://bitbucket.org/galaxy/galaxy-central/pull-requests/352/implement-plugin-framework-and-plugins-for/diff
- ~/galaxy/config/job_metrics_conf.xml

**Comment by HadleyKing** [comment]
~/galaxy/config/job_metrics_conf.xml
