### ISSUE TITLE
xref

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/galaxy#22]
Populate the `xref` section in the `description_domain`

https://github.com/biocompute-objects/galaxy/blob/cbbe81946233e1e7ac625fc732115b5c23028fa8/lib/galaxy/webapps/galaxy/api/workflows.py#L1155

**Comment by nsoranzo** [comment]
If these are going to be user-supplied, they can be an optional parameter of `export_invocation_bco()`, i.e. to be extracted from `kwd` with something like:

```python
'xref': kwd.get('xref', []),
```

When we add an UI on top of the API, the form used to generate the BCO will have a field to add the xrefs.

**Comment by HadleyKing** [comment]
Link to #25
