### ISSUE TITLE
Figure out Webapp Mapper

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/galaxy#3]
Figure out what this is for and how to use for BCO development.
https://github.com/biocompute-objects/galaxy/blob/ead0cc81eed98a6a257e36470f10bfdf176d6c86/lib/galaxy/webapps/galaxy/buildapp.py#L346-L351

**Comment by nsoranzo** [comment]
This is needed to map the `GET /api/histories/<history_id>/export_bco` REST API call to `lib/galaxy/webapps/galaxy/api/histories.py:HistoriesController.export_bco()` method, see https://routes.readthedocs.io/
