### ISSUE TITLE
BCO as an object in history

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/galaxy#30]
How do we make BCO an object in the user history? Like the workflow extraction?

**Comment by nsoranzo** [comment]
Do you mean a menu entry?

**Comment by HadleyKing** [comment]
No, like a workflow object.

**Comment by nsoranzo** [comment]
These live in database tables and are mutable, while (history) datasets are not modifiable after creation.

**Comment by HadleyKing** [comment]
Won't implement
