### ISSUE TITLE
Modify .gitignore

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/galaxy#6]
Need to modify the ignore files and settings so collaboration is possible and the default settings are not instated on a clone of this branch.

**Comment by HadleyKing** [comment]
- remove tool_config.xml from .gitignore

**Comment by HadleyKing** [comment]
I have a few questions about this issue:
1) Does it make sense to modify the `.gitignore` files to be able to share configurations across different instances of the same deployment? 
2) How much of the core code has to be modified to be able to do this? 
3) is there a better, or more accepted way to share development configurations?

**Comment by HadleyKing** [comment]
@nsoranzo Any advice on these questions?

**Comment by nsoranzo** [comment]
I'd keep configurations to a separate repo, especially if we are going to use this repo to open PRs against the upstream Galaxy repo.

**Comment by HadleyKing** [comment]
@haoqianglyu 
Please see comment above. Do not modify the configuration files here. You can create a separate fork for that.
