### ISSUE TITLE
BCO export, all history data through Galaxy environment variables?

### ISSUE THREAD

**Issue by agbiotec** [biocompute-objects/galaxy#7]
ISSUE REFERS TO:
commit 0773fd64193540fe6990d2b8c1f4df38ddd198a8
https://github.com/biocompute-objects/galaxy/pull/2/commits/0773fd64193540fe6990d2b8c1f4df38ddd198a8

I see that the added code exports the skeleton json of the BCO, enriched with data from the history that are pulled in from Galaxy environment variables. 

The question is whether we could get everything we need from the history data through these environment variables? Can we go as deep as needed into the internal history json, and pull any element needed ?

For example, .steps.outputs.name or .steps.tool_shed_repository.name  (using JSON query notation here).

**Comment by HadleyKing** [comment]
@agbiotec 
See issue #4 where I have taken a stab at this. The syntax is probably all wrong but I think the intention should be clear for most lines. If we are able to take it item by item I believe this can be accomplished in the next couple of weeks.

**Comment by HadleyKing** [comment]
See b038b7626181737383cf8e49edbd2279e51fb854
